version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ELASTIC_PASSWORD=MagicWord
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
  jenkins:
    build:
      context: .
    environment:
      - AWS_REGION=$AWS_DEFAULT_REGION
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN
      - GITHUB_ORG=$GITHUB_ORG
      - GITHUB_USER=$GITHUB_USER
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - ELASTICSEARCH_HOST=http://elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=MagicWord
      - ELASTICSEARCH_KEY=jenkins/jenkins
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
